const api_url: any = 'https://localhost:7178/';
const front_url: any = 'http://192.168.1.19/chronosys';
export const environment = {
    production: true,
    /* -------------------------------------------------------------------------- */
    /*                                 LES ROUTES                                 */
    /* -------------------------------------------------------------------------- */
    API_BASE_URL_GENERAL: `${api_url}/api/v1/`,
    API_BASE_URL_USERS: `${api_url}/api_user/`,
    API_BASE_URL_PARAMETRAGE: `${api_url}/api_parametrage/`,
    API_BASE_URL_ImagesEssai: `${api_url}/images/ficheessais/`,
    API_BASE_URL_ImagesInspection: `${api_url}/images/inspections/`,
    unique_claim: 'Vnh0ohaeHj76hV4ctMU6IXNlwpK8pKusj7618QJKKj',
    /* -------------------------------------------------------------------------- */
    /*                                les variables                               */
    /* -------------------------------------------------------------------------- */
    /* -------------------------- Les rôles du système pour les guards et les ngif des composants -------------------------- */
    id_role_controller: '2',
    id_role_verfi: '7',
    id_role_superadministrateur: '2', // 1 en base64 => "MQ==" puis md5
    id_role_rtc: '3',
    id_role_gestionnaire_produits: 'f7947d50da7a043693a592b4db43b0a1', // 4 en base64 => "NA==" puis md5
    CRYPTAGE_KEY:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6ImFkbWluIiwibmJmIjoxNTY5NjA3MjcxLCJleHAiOjE1Njk2OTM2NzEsImlhdCI6MTU2OTYwNzI3MX0.KS3v5g8i9flucjOUcmiWwYrAKtS0zc8j-g0_HbqVh6U',
    months: [
        'Janvier',
        'Février',
        'Mars',
        'Avril',
        'Mai',
        'Juin',
        'Juillet',
        'Août',
        'Septembre',
        'Octobre',
        'Novembre',
        'Décembre',
    ],
    /* -------------------------------------------------------------------------- */
    /*                                  LES APIS                                  */
    /* -------------------------------------------------------------------------- */
    api: {
        ville: {
            afficher: 'AfficherVille',
            ajouter: 'AjouterVille',
            supprimer: 'SupprimerVille',
            modifier: 'ModifierVille',
            restaurer: 'RestaurerVille',
        },
        pays: {
            afficher: 'AfficherPays',
            ajouter: 'AjouterPays',
            supprimer: 'SupprimerPays',
            modifier: 'ModifierPays',
            restaurer: 'RestaurerPays',
        },
        /* --------------------------------- general -------------------------------- */
        general: {
            telecharger: 'TelechargerDocument',
            LoadRolesList: 'LoadRolesList',
            LoadCountDashboard: 'LoadCountDashboard',
            AfficherLogs: 'AfficherLogs',
        },
        user: {
            /* ---------------------------------- crud ---------------------------------- */
            login: 'Users/Login',
            save: 'users/insert',
            modifie: 'users/update',
            modifier_password: 'users/UpdatePassWord',
            afficher_image: 'users/AfficherImageUtilisateur',
            afficher: 'users/search',
            supprimer: 'users/delete',
            GetAllByRoleController: 'users/GetAllByRoleController'
        },
        dashboards: {
            tableaux: 'dashboards/tableaux',
        },
        role: {
            search: 'roles/search',
            afficherAll: 'roles/GetAll',
            AjouterRole: 'roles/insert',
            ModifieRole: 'roles/update',
            supprimer: 'roles/delete',
        },
        permissions: {
            getAllbyRole: 'permissions/GetAllByRole',
            save: 'permissions/save',
        },
        parametrage: {
            search: 'parametrages/search',
            afficherAll: 'parametrages/GetAll',
            Ajouter: 'parametrages/insert',
            Modifie: 'parametrages/update',
            supprimer: 'parametrages/delete',
        },
        inspection: {
            getHeaderNamesFromCSV: 'inspections/getHeaderNamesFromCSV',
            UploadFileAndData: 'inspections/UploadFileAndData',
            search: 'inspections/search',
            afficherAll: 'inspections/GetAll',
            Ajouterinspection: 'inspections/Insertinspection',
            InsertStepper: 'inspections/InsertStepper',
            Modifie: 'inspections/update',
            supprimer: 'inspections/delete',
            InspectionById: 'inspections/InspectionById',
            DemarrerInspection: 'inspections/DemarrerInspection',
            DecisionRtc: 'inspections/DecisionRtc',
            ArreterInspection: 'inspections/ArreterInspection',
            ClosingeInspection: 'inspections/ClosingeInspection',
            AffecterInspection: 'inspections/AffecterInspection',
            RemoveImages: 'inspections/RemoveImages',
            ValidationInspection: 'inspections/ValidationInspection',
        },
        clients: {
            getHeaderNamesFromCSV: 'clients/getHeaderNamesFromCSV',
            UploadFileAndData: 'clients/UploadFileAndData',
            search: 'clients/search',
            searchByName: 'clients/SearchByName',
            afficherAll: 'clients/GetAll',
            Ajouter: 'clients/insert',
            Modifie: 'clients/update',
            supprimer: 'clients/delete',
        },
        vehicules: {
            getHeaderNamesFromCSV: 'vehicules/getHeaderNamesFromCSV',
            UploadFileAndData: 'vehicules/UploadFileAndData',
            search: 'vehicules/search',
            searchByImmatri: 'vehicules/SearchByImmari',
            afficherAll: 'vehicules/GetAll',
            Ajouter: 'vehicules/insert',
            Modifie: 'vehicules/update',
            supprimer: 'vehicules/delete',
            AutoCompletChamps: 'vehicules/AutoCompletChamps'
        },
        essai: {
            load: 'Essais/load',
            search: 'Essais/search',
            afficherAll: 'Essais/GetAll',
            Ajouter: 'Essais/insert',
            Modifie: 'Essais/update',
            supprimer: 'Essais/delete',
            validationEssai: 'Essais/ValidationEssai',
            InsertStepper: 'Essais/InsertStepper',
            DemarrerVerification: 'Essais/DemarrerVerification',
            DecisionRtc: 'Essais/DecisionRtc',
        },
        annexe: {
            afficherAll: 'Annexe/GetCheckListInputByEssai',
            Ajouter: 'Annexe/insert',
            Modifie: 'Annexe/update',
            Save: 'Annexe/Save',
            Load: 'Annexe/Load',
        },
        mesure: {
            afficherAll: 'Mesure/GetInputMesureByEssai',
            Ajouter: 'Mesure/insert',
            Modifie: 'Mesure/update',
            Save: 'Mesure/Save',
            Load: 'Mesure/Load',
        },
        ordreService: {
            getHeaderNamesFromCSV: 'OrdreService/getHeaderNamesFromCSV',
            UploadFileAndData: 'OrdreService/UploadFileAndData',
            search: 'OrdreService/search',
            GetHistoriques: 'OrdreService/GetHistoriques',
            afficherAll: 'OrdreService/GetAll',
            Ajouter: 'OrdreService/insert',
            Modifie: 'OrdreService/update',
            supprimer: 'OrdreService/delete',
            load: 'OrdreService/load',
            GetAllTypeInspections: 'OrdreService/GetAllTypeInspections',
            GetAllTypeDAccord: 'OrdreService/GetAllTypeDAccord',
            SendEmailOds: 'OrdreService/SendEmailOds',
            Reouvrirods: 'OrdreService/Reouvrirods'
        },
        declaration:{
            search: 'Declaration/search',
            afficherAll: 'Declaration/GetAll',
            Ajouter : 'Declaration/insert',
            Modifie:  'Declaration/update',
            supprimer :'Declaration/delete',
            changerStatut :'Declaration/changer-statut'
        },
        typeOrdreService: {
            Search: 'TypeOrdreService/search',
            GetAll: 'TypeOrdreService/GetAll',
            Add: 'TypeOrdreService/insert',
            Update: 'TypeOrdreService/update',
            Delete: 'TypeOrdreService/delete',
        },
        TypeCapteurVitesse: {
            Search: 'TypeCapteurVitesse/search',
            GetAll: 'TypeCapteurVitesse/GetAll',
            Add: 'TypeCapteurVitesse/insert',
            Update: 'TypeCapteurVitesse/update',
            Delete: 'TypeCapteurVitesse/delete',
        },
        OrganismService: {
            Search: 'Organismes/search',
            GetAll: 'Organismes/GetAll',
            Add: 'Organismes/insert',
            Update: 'Organismes/update',
            Delete: 'Organismes/delete',
        },

        CertificatService: {
            Search: 'Certificat/Search',
            GetCertifByIdInspection: 'Certificat/GetCertifByIdInspection',
            GetAll: 'Certificat/GetAll',
            Add: 'Certificat/Insert',
            Update: 'Certificat/Update',
            Delete: 'Certificat/Delete',
        },
        phrasier: {
            search: 'phrasiers/search',
            afficherAll: 'phrasiers/GetAll',
            AjouterPhrasier: 'phrasiers/insert',
            ModifiePhrasier: 'phrasiers/update',
            supprimer: 'phrasiers/delete',
        },
        testMilleMetre: {
            Search: 'TestMilleMetres/search',
            GetAll: 'TestMilleMetres/getAll',
            LoadByIdEssai: 'TestMilleMetres/LoadByIdEssai',
            Add: 'TestMilleMetres/insert',
            Update: 'TestMilleMetres/update',
            Delete: 'TestMilleMetres/delete',
        },
        equipement: {
            search: 'equipements/search',
            afficherAll: 'equipements/GetAll',
            AjouterEquipement: 'equipements/insert',
            ModifieEquipement: 'equipements/update',
            SupprimerEquipement: 'equipements/delete',
        },
        reclamation: {
            search: 'reclamations/search',
            afficherAll: 'reclamations/GetAll',
            ajouterReclamation: 'reclamations/insert',
            ModifieReclamation: 'reclamations/update',
            supprimerReclamtion: 'reclamations/delete',
            ReclamationById: 'reclamations/ReclamationById',
        },
        ligne: {
            Search: 'lignes/search',
            GetAll: 'lignes/GetAll',
            Add: 'lignes/insert',
            Update: 'lignes/update',
            Delete: 'lignes/delete',
        },
        typeOrganisme: {
            Search: 'TypeOrganisme/search',
            GetAll: 'TypeOrganisme/GetAll',
            Add: 'TypeOrganisme/insert',
            Update: 'TypeOrganisme/update',
            Delete: 'TypeOrganisme/delete',
        },
        fabriquant: {
            search: 'fabriquants/search',
            afficherAllFabriquant: 'fabriquants/GetAll',
            AjouterFabriquant: 'fabriquants/insert',
            ModifieFabriquant: 'fabriquants/update',
            SupprimerFabriquant: 'fabriquants/delete',
        },
        marque: {
            searchMarque: 'marques/search',
            afficherAllMarque: 'marques/GetAll',
            AjouterMarque: 'marques/insert',
            ModifierMarque: 'marques/update',
            SupprimerMarque: 'marques/delete',
        },
        taille: {
            searchTaille: 'tailles/search',
            afficherAllTaille: 'tailles/GetAll',
            AjouterTaille: 'tailles/insert',
            ModifierTaille: 'tailles/update',
            SupprimerTaille: 'tailles/delete',
        },
        typeAccord: {
            searchTypeAccord: 'typeAccords/search',
            afficherAllTypeAccord: 'typeAccords/GetAll',
            AjouterTypeAccord: 'typeAccords/insert',
            ModifierTypeAccord: 'typeAccords/update',
            SupprimerTypeAccord: 'typeAccords/delete',
        },
        typeInspection: {
            searchTypeInspection: 'typeInspections/search',
            afficherAllTypeInspection: 'typeInspections/GetAll',
            AjouterTypeInspection: 'typeInspections/insert',
            ModifierTypeInspection: 'typeInspections/update',
            SupprimerTypeInspection: 'typeInspections/delete',
        },
        typeMarque: {
            searchTypeMarque: 'typeMarques/search',
            afficherAllTypeMarque: 'typeMarques/GetAll',
            AjouterTypeMarque: 'typeMarques/insert',
            ModifierTypeMarque: 'typeMarques/update',
            SupprimerTypeMarque: 'typeMarques/delete',
            GetTypeMarqueByIdMarque: 'typeMarques/GetTypeMarqueByIdMarque',
        },
        numHomologation: {
            searchNumHomologation: 'numHomologations/search',
            afficherAllNumHomologation: 'numHomologations/GetAll',
            AjouterNumHomologation: 'numHomologations/insert',
            ModifierNumHomologation: 'numHomologations/update',
            SupprimerNumHomologation: 'numHomologations/delete',
            GetNumHomologationByIdTypeMarque: 'numHomologations/GetNumHomologationByIdTypeMarque',
        },
        materielUtilise: {
            GetAll: 'MaterielUtilises/GetMaterielUtiliseByIdInspection',
            Save: 'MaterielUtilises/SaveMaterielUtiliseForInspection',
        },
    },
    supperadmin: 'Supper admin',
    Administateur: 'Administateur',
    max_value_to_compress: 2200,
    value_to_compress: 2000000,
    html_config: '',
};
